// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SlangApiRest.Database;

#nullable disable

namespace SlangApiRest.Migrations
{
    [DbContext(typeof(SlangDbContext))]
    partial class SlangDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SlangApiRest.ModelsDB.Slang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Slangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Meaning = "Cuando las vacas vuelen",
                            Phrase = "That'll be the day"
                        },
                        new
                        {
                            Id = 2,
                            Meaning = "Ya basta",
                            Phrase = "Enough is enough"
                        },
                        new
                        {
                            Id = 3,
                            Meaning = "Dejar de pensar en ...",
                            Phrase = "Get you mind off"
                        },
                        new
                        {
                            Id = 4,
                            Meaning = "Te odio",
                            Phrase = "I hate your guts"
                        },
                        new
                        {
                            Id = 5,
                            Meaning = "Muy nervioso",
                            Phrase = "On edge"
                        },
                        new
                        {
                            Id = 6,
                            Meaning = "No tener el coraje de hacer algo",
                            Phrase = "Not have the guts"
                        },
                        new
                        {
                            Id = 7,
                            Meaning = "Broma interna de un grupo específico",
                            Phrase = "Inside joke"
                        },
                        new
                        {
                            Id = 8,
                            Meaning = "De la vieja escuela",
                            Phrase = "Old school"
                        },
                        new
                        {
                            Id = 9,
                            Meaning = "Aparecer",
                            Phrase = "Show up"
                        },
                        new
                        {
                            Id = 10,
                            Meaning = "Presumir",
                            Phrase = "Flex"
                        },
                        new
                        {
                            Id = 11,
                            Meaning = "Oye",
                            Phrase = "Yo"
                        },
                        new
                        {
                            Id = 12,
                            Meaning = "Besar",
                            Phrase = "Make out"
                        },
                        new
                        {
                            Id = 13,
                            Meaning = "Cuerpo",
                            Phrase = "Bod"
                        },
                        new
                        {
                            Id = 14,
                            Meaning = "Bombón",
                            Phrase = "Hottie"
                        },
                        new
                        {
                            Id = 15,
                            Meaning = "Ya me cansé / Ya lo he dejado",
                            Phrase = "I'm done with it"
                        },
                        new
                        {
                            Id = 16,
                            Meaning = "Informado / Al tanto",
                            Phrase = "Woke / Aware"
                        },
                        new
                        {
                            Id = 17,
                            Meaning = "Ansioso / Nervioso",
                            Phrase = "Antsy"
                        },
                        new
                        {
                            Id = 18,
                            Meaning = "Me voy de aquí",
                            Phrase = "I'm outta here"
                        },
                        new
                        {
                            Id = 19,
                            Meaning = "Cerveza",
                            Phrase = "Brew"
                        },
                        new
                        {
                            Id = 20,
                            Meaning = "Novato / Principiante",
                            Phrase = "Rookie"
                        },
                        new
                        {
                            Id = 21,
                            Meaning = "Fiesta / Festejo",
                            Phrase = "Shindig"
                        },
                        new
                        {
                            Id = 22,
                            Meaning = "Genial / Grandioso",
                            Phrase = "Swell"
                        },
                        new
                        {
                            Id = 23,
                            Meaning = "Hacer un trato / Cerrar un trato",
                            Phrase = "Cut a deal"
                        },
                        new
                        {
                            Id = 24,
                            Meaning = "Amigo / Camarada",
                            Phrase = "Homey"
                        },
                        new
                        {
                            Id = 25,
                            Meaning = "Claro y simple",
                            Phrase = "Cut and dry"
                        },
                        new
                        {
                            Id = 26,
                            Meaning = "Inconsciente",
                            Phrase = "Passed out"
                        },
                        new
                        {
                            Id = 27,
                            Meaning = "Épico / Impresionante / Increíble",
                            Phrase = "Epic"
                        },
                        new
                        {
                            Id = 28,
                            Meaning = "Inteligente / Genio",
                            Phrase = "Whiz"
                        },
                        new
                        {
                            Id = 29,
                            Meaning = "Trabajo / Chamba",
                            Phrase = "Gig"
                        },
                        new
                        {
                            Id = 30,
                            Meaning = "Chica / Jóven",
                            Phrase = "Chick"
                        },
                        new
                        {
                            Id = 31,
                            Meaning = "Loco / Locura",
                            Phrase = "Nuts"
                        },
                        new
                        {
                            Id = 32,
                            Meaning = "Malo / Loco",
                            Phrase = "Wack"
                        },
                        new
                        {
                            Id = 33,
                            Meaning = "Simple / Aburrido",
                            Phrase = "Basic"
                        },
                        new
                        {
                            Id = 34,
                            Meaning = "Antro / Bar baráto",
                            Phrase = "Joint"
                        },
                        new
                        {
                            Id = 35,
                            Meaning = "Tonto / Tontería / Payaso",
                            Phrase = "Goof"
                        },
                        new
                        {
                            Id = 36,
                            Meaning = "Autopista",
                            Phrase = "Freeway"
                        },
                        new
                        {
                            Id = 37,
                            Meaning = "Resumir / Recapitular",
                            Phrase = "Recap"
                        },
                        new
                        {
                            Id = 38,
                            Meaning = "Estoy Emocionado",
                            Phrase = "I'm Amped"
                        },
                        new
                        {
                            Id = 39,
                            Meaning = "Vacaciones",
                            Phrase = "Vacay"
                        },
                        new
                        {
                            Id = 40,
                            Meaning = "Ella es guapa",
                            Phrase = "She is a Looker"
                        },
                        new
                        {
                            Id = 41,
                            Meaning = "Exclusivo",
                            Phrase = "Upscale"
                        },
                        new
                        {
                            Id = 42,
                            Meaning = "Auto BMW",
                            Phrase = "Beemer"
                        },
                        new
                        {
                            Id = 43,
                            Meaning = "Dinero",
                            Phrase = "Dough"
                        },
                        new
                        {
                            Id = 44,
                            Meaning = "Tímido / Introvertido",
                            Phrase = "Wallflower"
                        },
                        new
                        {
                            Id = 45,
                            Meaning = "Nerd / Cerebrito",
                            Phrase = "Geek"
                        },
                        new
                        {
                            Id = 46,
                            Meaning = "Loco",
                            Phrase = "Cray"
                        },
                        new
                        {
                            Id = 47,
                            Meaning = "Alboroto / Ruido molesto / Barullo / Escándalo",
                            Phrase = "Racket"
                        },
                        new
                        {
                            Id = 48,
                            Meaning = "Alguien muy gracioso",
                            Phrase = "Riot"
                        },
                        new
                        {
                            Id = 49,
                            Meaning = "Vibras",
                            Phrase = "Vibes"
                        },
                        new
                        {
                            Id = 50,
                            Meaning = "Todos ustedes",
                            Phrase = "Y'all"
                        },
                        new
                        {
                            Id = 51,
                            Meaning = "Muy",
                            Phrase = "Hella"
                        },
                        new
                        {
                            Id = 52,
                            Meaning = "Padres / Muchachos / Gente",
                            Phrase = "Folks"
                        },
                        new
                        {
                            Id = 53,
                            Meaning = "Hasta luego",
                            Phrase = "Later"
                        },
                        new
                        {
                            Id = 54,
                            Meaning = "Alguien raro",
                            Phrase = "Weirdo"
                        },
                        new
                        {
                            Id = 55,
                            Meaning = "Bocadillos / Antojos",
                            Phrase = "Munchies"
                        },
                        new
                        {
                            Id = 56,
                            Meaning = "Verduras",
                            Phrase = "Veggies"
                        },
                        new
                        {
                            Id = 57,
                            Meaning = "Melodramático / Exagerado",
                            Phrase = "Drama queen"
                        },
                        new
                        {
                            Id = 58,
                            Meaning = "Oh dios mío",
                            Phrase = "Oh my godness / Oh my god"
                        },
                        new
                        {
                            Id = 59,
                            Meaning = "Acompañar / colarse",
                            Phrase = "Tag along"
                        },
                        new
                        {
                            Id = 60,
                            Meaning = "No tener mucho dinero / Sin plata",
                            Phrase = "Short on cash"
                        },
                        new
                        {
                            Id = 61,
                            Meaning = "Súbelo fuerte y rápido",
                            Phrase = "Crank it up"
                        },
                        new
                        {
                            Id = 62,
                            Meaning = "En curso / En proceso",
                            Phrase = "In the works"
                        },
                        new
                        {
                            Id = 63,
                            Meaning = "Una persona destacada / Una maravilla",
                            Phrase = "A class act"
                        },
                        new
                        {
                            Id = 64,
                            Meaning = "Fastidiado / Disgustado / Decepcionado / Molesto",
                            Phrase = "Bummed"
                        },
                        new
                        {
                            Id = 65,
                            Meaning = "Ponerse loco",
                            Phrase = "Freak out"
                        },
                        new
                        {
                            Id = 66,
                            Meaning = "Sospechoso",
                            Phrase = "Shady"
                        },
                        new
                        {
                            Id = 67,
                            Meaning = "Patético / Lamentable",
                            Phrase = "Lame"
                        },
                        new
                        {
                            Id = 68,
                            Meaning = "Relajado / Despreocupado / Muy tranquilo",
                            Phrase = "Mellow"
                        },
                        new
                        {
                            Id = 69,
                            Meaning = "Desocupar / Irse",
                            Phrase = "Clear out"
                        },
                        new
                        {
                            Id = 70,
                            Meaning = "Refrescarse / Tranquilizarse",
                            Phrase = "Cool off"
                        },
                        new
                        {
                            Id = 71,
                            Meaning = "Tesorito / Lindura",
                            Phrase = "Cutie pie"
                        },
                        new
                        {
                            Id = 72,
                            Meaning = "Una maravilla",
                            Phrase = "A blast"
                        },
                        new
                        {
                            Id = 73,
                            Meaning = "Tomarse un descanso / Relajarse",
                            Phrase = "Take a load off"
                        },
                        new
                        {
                            Id = 74,
                            Meaning = "Sé tu mismo",
                            Phrase = "Keep it real"
                        },
                        new
                        {
                            Id = 75,
                            Meaning = "Confesar / Admitir",
                            Phrase = "Fess up"
                        },
                        new
                        {
                            Id = 76,
                            Meaning = "Acaba el trago",
                            Phrase = "Drink up"
                        },
                        new
                        {
                            Id = 77,
                            Meaning = "¿Qué hay de bueno?",
                            Phrase = "What's good?"
                        },
                        new
                        {
                            Id = 78,
                            Meaning = "Salir",
                            Phrase = "Bounce"
                        },
                        new
                        {
                            Id = 79,
                            Meaning = "Perezoso",
                            Phrase = "Slouch"
                        },
                        new
                        {
                            Id = 80,
                            Meaning = "Entrometido / Curioso / Chepito / Sapo",
                            Phrase = "Nosy"
                        },
                        new
                        {
                            Id = 81,
                            Meaning = "Tener un nivel decente en algo",
                            Phrase = "Decent"
                        },
                        new
                        {
                            Id = 82,
                            Meaning = "Un fastidio / Desagrado / Aburrido",
                            Phrase = "A drag"
                        },
                        new
                        {
                            Id = 83,
                            Meaning = "Molestia",
                            Phrase = "Hassle"
                        },
                        new
                        {
                            Id = 84,
                            Meaning = "Cobarde / Desertor",
                            Phrase = "Quitter"
                        },
                        new
                        {
                            Id = 85,
                            Meaning = "Irse / Despegar",
                            Phrase = "Take off"
                        },
                        new
                        {
                            Id = 86,
                            Meaning = "Un buen jugador / Alguien con buena actitud",
                            Phrase = "A good sport"
                        },
                        new
                        {
                            Id = 87,
                            Meaning = "Pasar la noche / Quedarse a dormir",
                            Phrase = "Sleep over"
                        },
                        new
                        {
                            Id = 88,
                            Meaning = "Quedarse dormido / Dormirse rápido",
                            Phrase = "Out like a light"
                        },
                        new
                        {
                            Id = 89,
                            Meaning = "Un gran chico / Muy bueno / Muy impresionante",
                            Phrase = "Hell of a guy"
                        },
                        new
                        {
                            Id = 90,
                            Meaning = "Dejarme esperando",
                            Phrase = "Leave me hanging"
                        },
                        new
                        {
                            Id = 91,
                            Meaning = "Onda / Vibra / Energía",
                            Phrase = "Vibe"
                        },
                        new
                        {
                            Id = 92,
                            Meaning = "Así se hace / Bien hecho",
                            Phrase = "Way to go"
                        },
                        new
                        {
                            Id = 93,
                            Meaning = "Estoy cansadísimo / Estoy exhausto / No puedo más",
                            Phrase = "I'm beat"
                        },
                        new
                        {
                            Id = 94,
                            Meaning = "Enfadado / Muy Enojado",
                            Phrase = "Pissed off"
                        },
                        new
                        {
                            Id = 95,
                            Meaning = "Esperar",
                            Phrase = "Hold on"
                        },
                        new
                        {
                            Id = 96,
                            Meaning = "Tranquilizarse / Calmarse",
                            Phrase = "Cool it"
                        },
                        new
                        {
                            Id = 97,
                            Meaning = "Salud / Brindis",
                            Phrase = "Cheers"
                        },
                        new
                        {
                            Id = 98,
                            Meaning = "Casarse",
                            Phrase = "Tie the knot"
                        },
                        new
                        {
                            Id = 99,
                            Meaning = "Yo invito",
                            Phrase = "It's on me"
                        },
                        new
                        {
                            Id = 100,
                            Meaning = "Relajarse",
                            Phrase = "Chill out"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
